version: "3.1"

language: "en"

pipeline:
  # Tokenizer to break the text into words (Whitespace-based)
- name: WhitespaceTokenizer
  case_sensitive: false

  # Regex-based entity features
- name: RegexFeaturizer
  case_sensitive: false

  # Syntactic and lexical features based on token positions
- name: LexicalSyntacticFeaturizer

  # Count Vectors Featurizer for word and n-gram features
- name: CountVectorsFeaturizer
  OOV_token: "[UNK]"    # Token for words not in the vocabulary
  min_ngram: 1
  max_ngram: 3    # Trigrams will help capture patterns in larger text
  max_features: 15000    # Increase to handle larger data

  # DIETClassifier with fine-tuned parameters for entity recognition and intent classification
- name: DIETClassifier
  epochs: 700    # Increase epochs to ensure convergence with large data
  constrain_similarities: true
  entity_recognition: true
  intent_classification: true
  entity_roles: true
  entity_groups: true
  random_seed: 42
  embedding_dimension: 128    # Increase dimensions to handle large data
  use_masked_language_model: false
  batch_size: 128    # Larger batch size for efficient training
  learning_rate: 0.002    # Lower learning rate for smoother convergence
  entities:
  - discipline
  - industry
  - keywords
  - duration
  - location
  - size

  # Synonym mapping for entities (like size, location types, etc.)
- name: EntitySynonymMapper

  # Fallback classifier for handling ambiguous queries
- name: FallbackClassifier
  threshold: 0.4    # Adjust for tolerance on low-confidence predictions
  ambiguity_threshold: 0.1    # Slightly increase tolerance for similar intents

  # Language model that boosts performance for large datasets (Optional)
- name: LanguageModelFeaturizer
  model_name: "bert"    # BERT model can be used to capture richer semantic features
  model_weights: "bert-base-uncased"

policies:
  # Memoization policy for remembering exact responses
- name: MemoizationPolicy
  max_history: 10

  # Transformer-based TEDPolicy for dialogue management
- name: TEDPolicy
  max_history: 10
  epochs: 500    # Increase epochs for more accurate dialogue flow learning
  batch_size: 128    # Increase batch size to match the dataset size

  # Rule-based policy for fallback and custom rules
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
assistant_id: 20241015-002319-ascent-carrier
