version: "3.1"

language: "en"

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  case_sensitive: false
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: "[UNK]"
  min_ngram: 1
  max_ngram: 2
  max_features: 10000
- name: DIETClassifier
  epochs: 500
  constrain_similarities: true
  entity_recognition: true
  random_seed: 42
  use_masked_language_model: false
  batch_size: 64
  embedding_dimension: 60
  intent_classification: true
  entity_roles: true
  entity_groups: true
  entities:
  - discipline
  - industry
  - keywords
  - duration
  - location
  - size
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.05

policies:
- name: MemoizationPolicy
  max_history: 10
- name: TEDPolicy
  max_history: 10
  epochs: 300
  batch_size: 64
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
assistant_id: 20241014-010512-frigid-fitting
