version: "3.1"

language: "en"

pipeline:
- name: SpacyNLP
  model: en_core_web_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexEntityExtractor
  case_sensitive: false
  use_lookup_tables: true
  use_regexes: true
  use_word_boundaries: true
  entities: ["duration", "size", "location"]
- name: CRFEntityExtractor
  features: [["low", "title", "upper"], ["low", "upper", "title", "digit", "pattern"], ["low", "upper", "title"]]
  BILOU_flag: true
- name: DIETClassifier
  epochs: 200
  entity_recognition: true
  random_seed: 42
  constrain_similarities: true
  use_masked_language_model: true
  entity_roles: true
  entity_groups: true
  entities: ["discipline", "industry", "keywords"]
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.05

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 200
- name: RulePolicy
assistant_id: 20241007-153825-amber-vertex
