version: "3.1"

language: "en"

pipeline:
  # Tokenizer to break the text into words (Whitespace-based)
- name: WhitespaceTokenizer
  case_sensitive: false

  # Regex-based entity features
- name: RegexFeaturizer
  case_sensitive: false

  # Syntactic and lexical features based on token positions
- name: LexicalSyntacticFeaturizer

  # Count Vectors Featurizer for word and n-gram features
- name: CountVectorsFeaturizer
  OOV_token: "[UNK]"
  min_ngram: 1
  max_ngram: 2

  # RegexEntityExtractor to capture structured entities using detailed patterns
- name: RegexEntityExtractor
  use_regexes: true
  use_lookup_tables: true
  regexes:
  - name: duration
    pattern: "(?i)\\b(\\d+\\s?(weeks?|wks?|week|))\\b"
  - name: location_type
    pattern: "(?i)\\b(remote|online|on[- ]?site|flexible)\\b"
  - name: size
    pattern: "(?i)\\b(small|medium|med|large|big)\\b"
  - name: industry
    pattern: "(?i)\\b(business|design(?: & arts)?|engineering|it(?: & computer science)?|law(?:, legal studies & justice)?|health|education|science|social sciences(?: & communication)?|food & hospitality|trades & services)\\b"
  - name: discipline
    pattern: "(?i)\\b(economics|human resources|management|accounting(?:, commerce & finance)?|hospitality(?:, tourism & retail)?|marketing(?:, advertising & public relations)?|animation(?:, visual effects & post production)?|creative arts|media studies|fashion design|film(?: & tv)?|graphic design(?: & visual arts)?|journalism(?: & writing)?|music(?: & performing arts)?|aerospace engineering|software engineering|automotive(?: & transport engineering)?|biomedical engineering|civil engineering(?: & construction)?|mechanical engineering|mechatronic engineering|electrical engineering|chemical engineering|industrial engineering|robotics engineering|environmental engineering|marine engineering|manufacturing engineering|mining engineering|artificial intelligence|computer graphics(?: & animations)?|computer systems(?: & networks)?|cyber security|data science|design(?: & user experience)?|video game development|criminal justice|corporate law|law enforcement|nursing|pharmacist|dentistry(?: & orthopediatrics)?|exercise(?: & sports science)?|midwifery|occupational therapy|paramedics|physiotherapy|psychology|primary teaching|secondary teaching|special education|tertiary education|astronomy|biochemistry|biology|chemistry|geology|genetics|food science|forensic science|environmental science|physics|marine science|veterinary science|criminology|international studies|languages(?: & linguistics)?|literature|philosophy|social work|politics|culinary arts|hotel management|carers|carpentry|electrician|plumbing|flooring(?:, plastering & tiling)?|heating(?:, ventilation & cooling)?|bricklaying(?: & stonemasonry)?|surveying)\\b"

  # DIETClassifier with BERT-based embeddings for enhanced contextual understanding
- name: DIETClassifier
  epochs: 300
  evaluate_every: 10  # Evaluate every 20 epochs
  patience: 5         # Stop if no improvement for 5 evaluations
  constrain_similarities: true
  entity_recognition: true
  intent_classification: true
  entity_roles: true
  entity_groups: true
  random_seed: 42
  embedding_dimension: 80
  batch_size: 64
  learning_rate: 0.002
  transformer_model: "bert-base-uncased"    # or another compatible BERT model
  entities:
  - discipline
  - industry
  - keywords
  - duration
  - location_type
  - size

  # Synonym mapper for entity normalization
- name: EntitySynonymMapper

  # Fallback classifier to handle ambiguous queries
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1

policies:
  # Memoization policy to remember exact responses
- name: MemoizationPolicy
  max_history: 5

  # Transformer-based TEDPolicy for dialogue management
- name: TEDPolicy
  max_history: 5
  epochs: 300
  batch_size: 64

  # Rule-based policy for fallback and custom rules
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
assistant_id: 20241027-095231-binary-duffel
